#include <Arduino.h>
#include <M5Unified.h>


// source code from ChatGPT, generated by Python code (modified from ChatGPT's one):
// https://colab.research.google.com/drive/1TaIiMXHg7wuIP13Lcu2kMngkYvkSL9mC?usp=sharing
#include "esp32_pos_prediction.c"

// option: predict_temp() as well

void setup() {
	M5.begin();

	float param[3];
  // test data
  param[0] = 1.0; param[1] = 479.0; param[2] = 1129.0; // Ton, v0, v1 -> 0.0mm @ 25[degC]
  printf("Pos: %f\n", predict_pos(param));

  param[0] = 1.0; param[1] = 473.0; param[2] = 1123.0; // Ton, v0, v1 -> 0.0mm @ 30[degC]
  printf("Pos: %f\n", predict_pos(param));

  param[0] = 1.0; param[1] = 472.0; param[2] = 1112.0; // Ton, v0, v1 -> 0.0mm @ 35[degC]
  printf("Pos: %f\n", predict_pos(param));

  param[0] = 1.0; param[1] = 461.0; param[2] = 1098.0; // Ton, v0, v1 -> 0.0mm @ 40[degC]
  printf("Pos: %f\n", predict_pos(param));

  param[0] = 3.0; param[1] = 375.0; param[2] = 800.0; // Ton, v0, v1 -> 3.0mm @ 25[degC]
  printf("Pos: %f\n", predict_pos(param));
}

void loop() {
}
