#include <Arduino.h>
#include <M5Unified.h>


// source code from ChatGPT, generated by Python code (modified from ChatGPT's one):
// https://colab.research.google.com/drive/1TaIiMXHg7wuIP13Lcu2kMngkYvkSL9mC?usp=sharing
#include "esp32_pos_prediction.c"

// 以下、同様にtempモデルのパラメータとpredict_temp関数を追加します

void setup() {
	M5.begin();

    // テストデータ
    float features[3] = {1.0, 479.0, 1129.0};
    float pos_prediction = predict_pos(features);
    Serial.print("Predicted Pos: ");
    Serial.println(pos_prediction);

    // float temp_prediction = predict_temp(features);
    // Serial.print("Predicted Temp: ");
    // Serial.println(temp_prediction);
}

void loop() {
}
